# Generated by Django 5.2.1 on 2025-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_slot', models.TimeField()),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('number', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editable_until', models.DateTimeField()),
            ],
        ),
    ]
