# Generated by Django 5.2.1 on 2025-06-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotteryresult',
            name='editable_until',
        ),
    ]
