# Generated by Django 5.2.1 on 2025-06-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_remove_lotteryresult_editable_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_seconds', models.IntegerField(default=0)),
            ],
        ),
    ]
